---
title: "Основы дистанционного зондирования и фотограмметрии"
subtitle: "Электронный учебно-методический ресурс"
author: "Карпачевский А.М."
date: today
page-layout: article
toc: false
---

# Добро пожаловать

Это электронный учебно-методический ресурс по основам дистанционного зондирования и фотограмметрии.  
Материал охватывает ключевые этапы обработки данных дистанционного зондирования, геопривязки, мозаикирования, построения моделей рельефа и фотограмметрической обработки в специализированных программных пакетах.

::: {.callout-tip}
## Как пользоваться ресурсом

- Для перехода между темами используйте боковую панель слева.
- Материал организован по разделам, которые можно изучать последовательно.
- Если вы уже знакомы с базовыми понятиями, можно переходить сразу к нужной практической теме.
:::

## Содержание курса

В состав ресурса входят следующие разделы:

1. [Паншарпенинг](Ref01_Pansharpening.qmd)
2. [Географическая привязка изображений](Ref02_Georeference.qmd)
3. [Создание мозаик](Ref03_Mosaicking.qmd)
4. [Основы фотограмметрии](Ref12_Photogrammetry.qmd)
5. [Обработка АФС в E-Foto](Ref13_Efoto.qmd)
6. [Построение ЦМР в E-Foto](Ref14_DEM.qmd)
7. [Photomod: обработка аэрофотосъёмки](Ref15_Photomod_aerial.qmd)
8. [Photomod: построение ЦМР](Ref16_Photomod_DEM.qmd)
9. [Photomod: работа с RPC](Ref17_Photomod_RPC.qmd)
10. [Agisoft Metashape: базовая обработка](Ref18_Metashape.qmd)
11. [Agisoft Metashape: обработка с RPC](Ref20_Metashape_RPC.qmd)
12. [Работа с LAS-данными](Ref19_Las.qmd)


## Для кого предназначен ресурс

Ресурс ориентирован на:

- студентов 2 курса кафедры картографии и геоинформатики географического факультета МГУ имени М.В. Ломоносова
- Любых пользователей, имеющих базовое представление о фотограмметрической обработке данных дистанционного зондирования

::: {.callout-note}
## Примечание

Структура ресурса может обновляться и дополняться новыми разделами, примерами и иллюстрациями.
:::